server:
  port: 8085


spring:
  application:
    name: LogCollectorService


  datasource:
    url: jdbc:postgresql://localhost:5432/log_db
    username: postgres
    password: post123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: log-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  

